# Generated by Django 5.2.6 on 2025-11-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='id_producto_inventario',
            new_name='producto_inventario',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='id_inventario',
        ),
        migrations.AddField(
            model_name='inventario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
