# Generated by Django 5.2.6 on 2025-12-05 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('stock_producto', models.IntegerField()),
                ('fecha_vencimiento_producto', models.DateField(blank=True, null=True)),
                ('descripcion_producto', models.TextField(blank=True, null=True)),
                ('categoria_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.categoriaproducto')),
            ],
        ),
    ]
