# Generated by Django 5.2.6 on 2025-11-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_producto', models.IntegerField()),
                ('fecha_vencimiento_producto', models.DateField(blank=True, null=True)),
                ('descripcion_producto', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
