# Generated by Django 5.2.7 on 2025-12-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_normalize_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_producto',
        ),
    ]
