# Generated by Django 5.2.6 on 2025-11-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('apellido_Cliente', models.CharField(max_length=100)),
                ('direccion_cliente', models.CharField(max_length=200)),
                ('telefono_cliente', models.CharField(max_length=15)),
                ('alergia_cliente', models.CharField(max_length=200)),
            ],
        ),
    ]
