# Generated by Django 5.2.7 on 2025-12-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rut_cliente',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
