# Generated by Django 5.2.7 on 2025-12-05 00:56

import cliente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='customer_id_number',
            field=models.CharField(default=cliente.models.generate_customer_id, max_length=10, unique=True),
        ),
    ]
