# Generated by Django 5.2.6 on 2025-11-17 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_cliente_id_cliente_cliente_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='apellido_Cliente',
            new_name='apellido_cliente',
        ),
    ]
