# Generated by Django 5.2.6 on 2025-11-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_rename_apellido_cliente_cliente_apellido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='alergia_cliente',
            field=models.TextField(max_length=200),
        ),
    ]
