# Generated by Django 5.2.6 on 2025-11-12 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0002_remove_empleado_id_empleado_empleado_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(max_length=100)),
                ('fecha_generacion_reporte', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('empleado_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
            ],
        ),
    ]
