# Generated by Django 5.2.6 on 2025-11-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=100)),
                ('apellido_empleado', models.CharField(max_length=100)),
                ('usuario_empleado', models.CharField(max_length=100)),
                ('contrasena_empleado', models.CharField(max_length=255)),
                ('rol_empleado', models.CharField(max_length=50)),
            ],
        ),
    ]
