# Generated by Django 5.2.6 on 2025-12-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=100)),
                ('apellido_empleado', models.CharField(max_length=100)),
                ('usuario_empleado', models.CharField(max_length=100, unique=True)),
                ('contrasena_empleado', models.CharField(max_length=255)),
                ('rol_empleado', models.CharField(choices=[('ENCARGADO_TIENDA', 'Encargado de tienda'), ('ENCARGADO_LOGISTICA', 'Encargado de logística'), ('ATENCION_CLIENTE', 'Atención al cliente')], max_length=50)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
