# Generated by Django 5.2.6 on 2025-11-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=100)),
                ('apellido_empleado', models.CharField(max_length=100)),
                ('usuario_empleado', models.CharField(max_length=100)),
                ('contraseña_empleado', models.CharField(max_length=255)),
                ('rol_empleado', models.CharField(max_length=50)),
            ],
        ),
    ]
