# Generated by Django 5.2.6 on 2025-11-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rol_empleado',
            field=models.CharField(choices=[('ENCARGADO_TIENDA', 'Encargado de tienda'), ('ENCARGADO_LOGISTICA', 'Encargado de logistica'), ('ATENCION_CLIENTE', 'Atencion a cliente')], max_length=50),
        ),
    ]
