# Generated by Django 5.2.6 on 2025-11-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_remove_empleado_id_empleado_empleado_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='contraseña_empleado',
            new_name='contrasena_empleado',
        ),
    ]
