# Generated by Django 5.2.6 on 2025-11-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_alter_empleado_rol_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rol_empleado',
            field=models.CharField(choices=[('Encargado tienda', 'ENCARGADO_TIENDA'), ('Encargado logistica', 'ENCARGADO_LOGISTICA'), ('Atencion cliente', 'ATENCION_CLIENTE')], max_length=50),
        ),
    ]
