# Generated by Django 5.2.6 on 2025-11-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_alter_empleado_rol_empleado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
