# Generated by Django 5.2.6 on 2025-11-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0005_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rol_empleado',
            field=models.CharField(choices=[('ENCARGADO_TIENDA', 'Encargado de tienda'), ('ENCARGADO_LOGISTICA', 'Encargado de logística'), ('ATENCION_CLIENTE', 'Atención al cliente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='usuario_empleado',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
