# Generated by Django 5.2.6 on 2025-11-12 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('empleado', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('estado_pedido', models.CharField(max_length=50)),
                ('fecha_creacion_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_pedido', models.DateTimeField(blank=True, null=True)),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('empleado_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_detalle', models.IntegerField()),
                ('precio_unitario_detalle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_producto_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
                ('id_pedido_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido')),
            ],
        ),
    ]
