# Generated by Django 5.2.6 on 2025-11-12 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_remove_cliente_id_cliente_cliente_id'),
        ('empleado', '0002_remove_empleado_id_empleado_empleado_id'),
        ('producto', '0002_remove_producto_id_producto_producto_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_pedido', models.CharField(max_length=50)),
                ('fecha_creacion_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_pedido', models.DateTimeField(blank=True, null=True)),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('empleado_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_detalle', models.IntegerField()),
                ('precio_unitario_detalle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
                ('pedido_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido')),
            ],
        ),
    ]
