# Generated by Django 5.2.6 on 2025-11-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_creacion_pedido',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_entrega_pedido',
            field=models.DateField(blank=True, null=True),
        ),
    ]
