# Generated by Django 5.2.7 on 2025-12-05 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('empleado', '0001_initial'),
        ('pedido', '0001_initial'),
        ('producto', '0002_producto_precio_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_entrega',
            new_name='fecha_reserva',
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad_detalle',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_unitario_detalle',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.producto'),
        ),
    ]
