# Generated by Django 5.2.6 on 2025-11-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_alter_pedido_fecha_creacion_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='total_pedido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
