# Generated by Django 5.2.7 on 2025-12-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_rename_fecha_entrega_reserva_fecha_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
