# Generated by Django 5.2.6 on 2025-11-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_alter_pedido_total_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'verbose_name': 'DetallePedido', 'verbose_name_plural': 'DetallesPedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
