# Generated by Django 5.2.7 on 2025-12-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_alter_reserva_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_reserva',
            new_name='fecha_entrega',
        ),
    ]
